### ISSUE TITLE
elan1200 

### ISSUE THREAD

**Issue by onejay09** [alexandred/VoodooI2C#58] opened 2018-01-26 20:36 UTC
2 finger click/drag only works the first time, could a deadzone for the buttons be added?
and 2 finger right click is intermittent when tapping, it works ok when two finger click is used

**Comment by alexandred** [comment] 2018-01-26 22:33
What do you mean "the first time"?

And the problem with the right click is known, I don't have a solution for it yet.

**Comment by onejay09** [comment] 2018-01-26 22:41
I can drag icons with my second finger while holding the click button down
with my fist finger, but it only works once from login, the cursor won't
move the second time I try.

**Comment by alexandred** [comment] 2018-01-26 22:42
You should come to the Gitter chatroom and upload the archives requested on the Troubleshooting page.

**Comment by alexandred** [comment] 2018-01-26 23:53
Closed as confirmed not a bug. Fixed by following the drag instructions here: https://voodooi2c.github.io/#Supported Gestures/Supported Gestures

**Closed** 2018-01-27 15:04 UTC
