### ISSUE TITLE
Reboot / Kernel Panic if boot without Verbose. Must verbose boot with VoodooI2C.kext

### ISSUE THREAD

**Issue by andreszerocross** [alexandred/VoodooI2C#131] opened 2018-11-04 13:45 UTC
At Mojave 10.14.1 will get Kernel Panic and early reboot with VoodooI2C.kext. I try to disable the kext and it will boot fine. And i try to boot with verbose with VoodooI2C.kext + voodooI2CHID.kext and it will boot fine too. So the problem is boot without verbose. If we boot without verbose then system will KP or EarlyReboot.

I use VoodooI2C.kext 2.1.4 version

**Comment by alexandred** [comment] 2018-11-04 13:48
Duplicate of https://github.com/alexandred/VoodooI2C/issues/128.

**Closed by alexandred** 2018-11-04 13:48 UTC
